image: golang:1.12-alpine3.10

variables:
  CGO_ENABLED: 0

build:
  stage: build
  script:
    - pwd
    - go env
    - go build -o binaries/dupe cmd/dupe/dupe.go
    - go build -o binaries/generate cmd/generate/generate.go
  artifacts:
    paths:
      - binaries/

test:
  stage: test
  script:
    - go test -v ./...

test-race:
  stage: test
  image: golang:1.12
  variables:
    CGO_ENABLED: 1
  script:
    - go test -race -v ./...
